display_name: Roxi
publisher_display_name: Roxi
identity_name: CC.Roxi.App
msix_version: 1.3.9.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us, zh-cn, ru-ru, fa-ir
protocol_activation: hiddify, v2ray, v2rayn, v2rayng, clash, clashmeta, sing-box
execution_alias: roxi
# CI will generate and inject certificate_path at build time
certificate_path:
certificate_password:
publisher: CN=Roxi, O=Roxi, C=US
install_certificate: "true"
enable_at_startup: "true"
startup_task:
  parameters: --autostart